# Generated by Django 3.2.7 on 2021-11-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
