# Generated by Django 3.2.7 on 2021-11-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20211119_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
