# Generated by Django 3.2.7 on 2021-11-20 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_producto_categoria'),
        ('ordenes', '0004_rename_producto_articuloorden_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.orden'),
        ),
        migrations.AlterField(
            model_name='articuloorden',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.producto'),
        ),
    ]
